"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ÓÇ∂](color_orange)\
$os\
$username\
[ÓÇ∞](bg:color_yellow fg:color_orange)\
$directory\
[ÓÇ∞](fg:color_yellow bg:color_aqua)\
${env_var.yazi_level}\
$git_branch\
$git_status\
[ÓÇ∞](fg:color_aqua bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[ÓÇ∞](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
[ÓÇ∞](fg:color_bg3 bg:color_bg1)\
$time\
[ÓÇ¥ ](fg:color_bg1)\
$line_break$character"""

# Insert a blank line between shell prompts
add_newline = true

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_aqua   = '#689d6a'
color_bg1    = '#3c3836'
color_bg3    = '#665c54'
color_blue   = '#458588'
color_fg0    = '#fbf1c7'
color_fg1    = '#000000'
color_green  = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red    = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = true
style    = "bg:color_orange fg:color_fg0"

    [os.symbols]
    Alpine           = "ÔåÄ"
    Amazon           = "Ôâ∞"
    Android          = "Óúé"
    Arch             = "Û∞£á"
    Artix            = "Û∞£á"
    CentOS           = "ÔåÑ"
    Debian           = "Û∞£ö"
    EndeavourOS      = "ÔÜó"
    Fedora           = "Û∞£õ"
    Gentoo           = "Û∞£®"
    Linux            = "Û∞åΩ"
    Macos            = "Û∞Äµ"
    Manjaro          = "Ôåí"
    Mint             = "Û∞£≠"
    Pop              = "Ôå™"
    Raspbian         = "Û∞êø"
    RedHatEnterprise = "Û±Ñõ"
    Redhat           = "Û±Ñõ"
    SUSE             = "Ôåî"
    Ubuntu           = "Û∞ïà"
    Windows          = "Û∞ç≤"

[username]
disabled   = true
format     = '[ $user ]($style)'
style_root = "bg:color_orange fg:color_fg0"
style_user = "bg:color_orange fg:color_fg0"

[directory]
format            = "[ $path ]($style)"
style             = "fg:color_fg1 bg:color_yellow"
truncation_length = 3
truncation_symbol = "‚Ä¶/"

[git_branch]
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'
style  = "bg:color_aqua"
symbol = "Ôêò"

[git_status]
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'
style  = "bg:color_aqua"

[nodejs]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "Óúò"

[c]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "Óòû "

[rust]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "Óû®"

[golang]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "Óòß"

[php]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "Óòà"

[java]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "Óâñ"

[kotlin]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "Óò¥"

[haskell]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "Óòü"

[python]
format             = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
pyenv_version_name = false
style              = "bg:color_blue"
symbol             = "ÓòÜ"

[docker_context]
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'
style  = "bg:color_bg3"
symbol = "Ôåà"

[conda]
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'
style  = "bg:color_bg3"

[env_var.yazi_level]
description = "Indicate the shell was launched by `yazi`"
disabled    = true
format      = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'
symbol      = "ü¶Ü"                                                 # Duck
variable    = "YAZI_LEVEL"

[time]
disabled    = true
format      = '[[ Ôê∫ $time ](fg:color_fg0 bg:color_bg1)]($style)'
style       = "bg:color_bg1"
time_format = "%R"

[line_break]
disabled = false

[character]
disabled                  = false
error_symbol              = '[Ôê≤](bold fg:color_red)'
success_symbol            = '[Ôê≤](bold fg:color_green)'
vimcmd_replace_one_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_replace_symbol     = '[Ôê¥](bold fg:color_purple)'
vimcmd_symbol             = '[Ôê¥](bold fg:color_green)'
vimcmd_visual_symbol      = '[Ôê¥](bold fg:color_yellow)'
